// Product Variant interfaces
export interface ProductVariantCreate {
  attributes: Record<string, any>;  // e.g., {size: "M", color: "Blue"}
  stock: number;
  price_adjustment?: number;  // Price difference from base (default: 0)
  sku?: string;
  images?: string[];  // Optional variant-specific images
}

export interface ProductVariant {
  variant_id: string;  // Auto-generated by backend
  attributes: Record<string, any>;
  stock: number;
  price_adjustment: number;
  sku: string | null;
  images: string[] | null;
}

export interface Product {
  id: string;
  name: string;
  price?: number;
  description?: string;
  category?: string;
  sku?: string;
  stock?: number;  // Used for single-variant products (backward compatible)
  is_active: boolean;
  images?: string[];
  attributes?: Record<string, any>;  // Used for single-variant products
  variants?: ProductVariant[];  // New: array of variants
  total_stock?: number;  // New: total stock across all variants
  created_at?: string;
  updated_at?: string;
  customer_id?: string;
}

export type AttributeType = 'text' | 'number' | 'select' | 'multi_select' | 'color' | 'boolean';

export interface AttributeDefinition {
  name: string;
  label: string;
  type: AttributeType;
  required: boolean;
  options?: string[];
  help_text?: string;
  placeholder?: string;
}

export interface CategoryConfig {
  category: string;
  display_name: string;
  icon: string;
  attributes: AttributeDefinition[];
}

export interface CreateProductRequest {
  name: string;
  price?: number;
  description?: string;
  category?: string;
  sku?: string;
  stock?: number;  // For single-variant products
  is_active?: boolean;
  attributes?: Record<string, any>;  // For single-variant products
  variants?: ProductVariantCreate[];  // For multi-variant products
}

export interface UpdateProductRequest {
  name?: string;
  price?: number;
  description?: string;
  category?: string;
  sku?: string;
  stock?: number;  // For single-variant products
  is_active?: boolean;
  attributes?: Record<string, any>;  // For single-variant products
  variants?: ProductVariantCreate[];  // For multi-variant products
}

export interface ProductListResponse {
  items: Product[];
  total: number;
  skip: number;
  limit: number;
}

export interface PresignedUrlResponse {
  presigned_url: string;
  image_url: string;
  s3_key: string;
}

export interface ProductFilters {
  search?: string;
  category?: string;
  is_active?: boolean;
}
